### PR TITLE
Example for generating complex with SMIRNOFF/AMBER FF.

### PR DESCRIPTION
**Pull request by nathanmlim**
This PR adds some code to give an example of how to create a forcefield parameterized `parmed.Structure` of the complex with the protein parameterized with AMBER forcefield parameters (`amber99sbldn.xml`) and the SMIRNOFF ligand. Also added some fairly basic tests to test the two main functions that generated the parmed.Structures

### CODE REVIEW

**Comment by nathanmlim** [comment]
I've used the `Forcefield` from this repo but didn't see an equivalent to 
smarty.forcefield_utils.create_system_from_molecule` on this repo. So that bit of smarty is still left in [here](https://github.com/open-forcefield-group/openforcefield/pull/11/files#diff-7e940574762b4c5280bc73250062806aR57)

**Comment by davidlmobley** [comment]
Thanks, @nathanmlim . Possibly that part didn't get migrated yet -- I can move that over tomorrow hopefully.

**Comment by davidlmobley** [comment]
Test fail because this doesn't install `smarty`, which I can resolve by moving the relevant functionality from `smarty` to `openforcefield`.

**Comment by davidlmobley** [comment]
Test passed. Making one more minor fix to READMEs and merging.

**Pull request merged**
