### PR TITLE
Updating jupyter notebooks to remove smarty dependencies

### PR DESCRIPTION
**Pull request by bannanc**
As per issue #12, many of the jupyter notebooks were moved from smarty with no changes. Also, I am now using python3 on my work desktop and found a few python2 things that I updated in the process.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Looks like it needs updating to master, @bannanc .

**Comment by bannanc** [comment]
I found a few more things to fix, including a number of places "smirff" still appears I'll update the title when it is ready to go

**Comment by bannanc** [comment]
@davidlmobley 
Ok, now I think this is ready to go, if you still agree can you merge it?

**Comment by davidlmobley** [comment]
Thanks, @bannanc . Lots of those pesky smirffs around. Nice work. I'll merge.

**Pull request merged**
