### PR TITLE
Fixing loadFile for forcefield with files in data directory

### PR DESCRIPTION
**Pull request by bannanc**
I'm addressing the issue #22. I'm taking advantage of the method get_data_filename from utils to get access to the data directory. 

The previous version seemed to look for a data directory at 
openforcefield/typing/engines/smirnoff/data/
instead of just
openforcefield/data/

### CODE REVIEW

**Comment by bannanc** [comment]
Also, @davidlmobley or @jchodera 
should we format the repository to require a code review before merging changes?

**Comment by davidlmobley** [comment]
@bannanc - can you verify that this exception handling syntax still raises a useful exception in the scenario that you specify the name of an FFXML file which is in NEITHER location? (e.g. a file that just doesn't exist?) Sometimes I forget what happens if a new exception of the same type (in this case, `IOError`) is raised within an `except` block which is already testing for the same error.

Otherwise, this looks good.

**Comment by davidlmobley** [comment]
I also just went in and protected `master` so that now status checks must pass before merging, pushes can't be made directly to master, and reviews are required except for admins. THanks.

**Comment by bannanc** [comment]
@davidlmobley I just did a test run:
```
from openforcefield.typing.engines.smirnoff import forcefield
ff = forcefield.ForceField('imaginary_file.ffxml')
```
This returns a `ValueErrror` here is the full error message:
```
ValueError: Sorry! /Users/bannanc/anaconda3/lib/python3.6/site-packages/openforcefield/data/imaginary_file.ffxml does not exist. If you just added it, you'll have to re-install
```

**Comment by jchodera** [comment]
Good catch on the data directory issues, @bannanc!

> should we format the repository to require a code review before merging changes?

Yes!

**Pull request merged**
